export enum EnvCollection {
    SERVER_PORT = "SERVER_PORT",
    JWT_ACCESS_TOKEN_SECRET = "JWT_ACCESS_TOKEN_SECRET",
    JWT_REFRESH_TOKEN_SECRET = "JWT_REFRESH_TOKEN_SECRET",
    DB_TYPE = "DB_TYPE",
    DB_HOST = "DB_HOST",
    DB_PORT = "DB_PORT",
    DB_USERNAME = "DB_USERNAME",
    DB_PASSWORD = "DB_PASSWORD",
    DB_NAME = "DB_NAME",
}